"""initial

Revision ID: c32716d8752a
Revises: 
Create Date: 2026-04-22 11:02:53.690863

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = 'c32716d8752a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allowed_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('icon', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('windows_path', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_allowed_programs_slug'), 'allowed_programs', ['slug'], unique=True)
    op.create_table('groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('telegram_id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('full_name', sqlmodel.sql.sqltypes.AutoString(length=200), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_telegram_id'), 'users', ['telegram_id'], unique=True)
    op.create_table('agent_releases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('channel', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('download_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=False),
    sa.Column('sha256', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('signature', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('min_protocol_version', sa.Integer(), nullable=False),
    sa.Column('released_at', sa.DateTime(), nullable=False),
    sa.Column('released_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['released_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('hostname', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('ip_local', sqlmodel.sql.sqltypes.AutoString(length=45), nullable=True),
    sa.Column('machine_fingerprint', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.Column('online', sa.Boolean(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('protected', sa.Boolean(), nullable=False),
    sa.Column('agent_version', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=True),
    sa.Column('update_channel', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('os_version', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('machine_fingerprint')
    )
    op.create_index(op.f('ix_pcs_group_id'), 'pcs', ['group_id'], unique=False)
    op.create_index(op.f('ix_pcs_last_seen'), 'pcs', ['last_seen'], unique=False)
    op.create_index(op.f('ix_pcs_online'), 'pcs', ['online'], unique=False)
    op.create_table('commands',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=False),
    sa.Column('command_type', sqlmodel.sql.sqltypes.AutoString(length=50), nullable=False),
    sa.Column('params', sa.JSON(), nullable=True),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=False),
    sa.Column('target_pc_id', sa.Integer(), nullable=True),
    sa.Column('target_group_id', sa.Integer(), nullable=True),
    sa.Column('issued_by', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['target_pc_id'], ['pcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commands_expires_at'), 'commands', ['expires_at'], unique=False)
    op.create_index(op.f('ix_commands_status'), 'commands', ['status'], unique=False)
    op.create_index(op.f('ix_commands_target_group_id'), 'commands', ['target_group_id'], unique=False)
    op.create_index(op.f('ix_commands_target_pc_id'), 'commands', ['target_pc_id'], unique=False)
    op.create_index(op.f('ix_commands_trace_id'), 'commands', ['trace_id'], unique=False)
    op.create_index(op.f('ix_commands_uuid'), 'commands', ['uuid'], unique=True)
    op.create_table('pc_group_memberships',
    sa.Column('pc_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['pc_id'], ['pcs.id'], ),
    sa.PrimaryKeyConstraint('pc_id', 'group_id')
    )
    op.create_table('tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('pc_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_used', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['pc_id'], ['pcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('command_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('command_id', sa.Integer(), nullable=False),
    sa.Column('pc_id', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('executed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['command_id'], ['commands.id'], ),
    sa.ForeignKeyConstraint(['pc_id'], ['pcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_command_results_command_id'), 'command_results', ['command_id'], unique=False)
    op.create_index(op.f('ix_command_results_pc_id'), 'command_results', ['pc_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_command_results_pc_id'), table_name='command_results')
    op.drop_index(op.f('ix_command_results_command_id'), table_name='command_results')
    op.drop_table('command_results')
    op.drop_table('tokens')
    op.drop_table('pc_group_memberships')
    op.drop_index(op.f('ix_commands_uuid'), table_name='commands')
    op.drop_index(op.f('ix_commands_trace_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_target_pc_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_target_group_id'), table_name='commands')
    op.drop_index(op.f('ix_commands_status'), table_name='commands')
    op.drop_index(op.f('ix_commands_expires_at'), table_name='commands')
    op.drop_table('commands')
    op.drop_index(op.f('ix_pcs_online'), table_name='pcs')
    op.drop_index(op.f('ix_pcs_last_seen'), table_name='pcs')
    op.drop_index(op.f('ix_pcs_group_id'), table_name='pcs')
    op.drop_table('pcs')
    op.drop_table('agent_releases')
    op.drop_index(op.f('ix_users_telegram_id'), table_name='users')
    op.drop_table('users')
    op.drop_table('groups')
    op.drop_index(op.f('ix_allowed_programs_slug'), table_name='allowed_programs')
    op.drop_table('allowed_programs')
    # ### end Alembic commands ###
